from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    path('',views.home,name='home'),
    path('s_login',views.s_login,name='student_login'),
    path('f_login',views.f_login,name='faculty_login'),
    path('f_match',views.f_match,name='faculty_match'),
    path('s_match',views.s_match,name='student_match'),
    path('a_login',views.a_login,name='admin_login'),
    path('a_match',views.a_match,name='admin_match'),
    path('a_addStudent',views.a_addStudent,name='addstudent'),
    path('a_addFaculty',views.a_addFaculty,name='addfaculty'),
    path('a_addFacultyDetails',views.a_addFacultyDetails,name='addfaculty'),
    path('a_addStudentDetails',views.a_addStudentDetails,name='addstudentdeatils'),
    path('a_delStudent',views.a_delStudent,name='addstudentdeatils'),
    path('a_delFaculty',views.a_delFaculty,name='addstudentdeatils'),
    path('a_showStudent',views.a_showStudent,name='showStudent'),
    path('a_showFaculty',views.a_showFaculty,name='showFaculty'),
    path('a_alertStudent',views.a_alertStudent,name='alertStudent'),
    path('a_alertFaculty',views.a_alertFaculty,name='alertFaculty'),
    path('a_alertAll',views.a_alertAll,name='alertAll'),
    path('f_markStudent',views.f_markStudent,name='markStudent'),
    path('f_submitAttendance',views.f_submitAttendance,name='submitAttendance'),
    path('f_showMarks',views.f_showMarks,name='submitAttendance'),
    path('f_submitMarks',views.f_submitMarks,name='submitMarks'),
    path('s_grievances',views.s_grievances,name='submitGrievances'),
    path('s_submitComplaint',views.s_submitComplaint,name='submitGrievances'),
    path('s_academic',views.s_academic,name='Academic'),
    path('s_showAttendance',views.s_showAttendance,name='showAttendance'),
    path('s_sendFeedback',views.s_sendFeedback,name='sendFeedback'),
    path('s_submitFeedback',views.s_submitFeedback,name='submitFeedback'),
    path('f_showToppers',views.f_showToppers,name='showToppers'),
    path('f_showAttendance',views.f_showAttendance,name='showAttendance'),
    path('s_results',views.s_result,name='Result'),
    path('f_notifyStudents',views.f_notifyStudents,name='notify'),
    path('f_notify',views.f_notify,name='notify'),
    path('s_assignments',views.s_assignments,name='assignments'),
    path('busChart',views.busChart,name='busChart'),
    path('syllabus',views.syllabus_list,name='syllabus_list'),
    path('timetable', views.timetable_list, name='timetable_list'),
    path('f_assignment', views.f_assignment, name='f_assignment'),
    path('assignments/', views.assignment_list, name='assignment_list'),
]
