# Generated by Django 4.1.5 on 2024-04-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_id', models.IntegerField()),
                ('f_image', models.ImageField(upload_to='')),
                ('f_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_id', models.IntegerField()),
                ('s_image', models.ImageField(upload_to='')),
                ('s_dob', models.DateField()),
            ],
        ),
    ]
