# Generated by Django 4.1.5 on 2024-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_image',
            field=models.ImageField(default='', upload_to='home/f_img'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_image',
            field=models.ImageField(default='', upload_to='home/s_img'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
