# Generated by Django 4.1.5 on 2024-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_faculty_f_image_alter_student_s_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='s_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
