# Generated by Django 5.0.4 on 2024-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faculty_f_alerts_student_s_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='s_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_totalAttendance',
            field=models.IntegerField(default=0),
        ),
    ]
