# Generated by Django 5.0.4 on 2024-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_studetails_student_s_attendance_student_s_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_attendance',
            field=models.IntegerField(),
        ),
    ]
