# Generated by Django 5.0.4 on 2024-05-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_faculty_f_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='a_alerts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
