# Generated by Django 5.0.4 on 2024-05-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_admin_a_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_AttdCD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_AttdCN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_AttdDBMS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_AttdOOPS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_AttdOS',
            field=models.IntegerField(default=0),
        ),
    ]
