# Generated by Django 5.0.4 on 2024-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_admin_a_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_percentage',
            field=models.FloatField(default=0),
        ),
    ]
