# Generated by Django 5.0.4 on 2024-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_student_s_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_AttdSWE',
            field=models.IntegerField(default=0),
        ),
    ]
