# Generated by Django 5.0.4 on 2024-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_student_s_attdswe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_alerts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
