# Generated by Django 5.0.4 on 2024-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_faculty_f_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_image',
            field=models.ImageField(blank=True, upload_to='home/s_img'),
        ),
    ]
