# Generated by Django 5.0.4 on 2024-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_student_s_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_branch',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='s_classrollno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='s_course',
            field=models.CharField(default='Btech', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='s_sec',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='s_sem',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='student',
            name='s_year',
            field=models.IntegerField(default=3),
        ),
    ]
