# Generated by Django 5.0.4 on 2024-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_student_s_branch_student_s_classrollno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_qualifications',
            field=models.CharField(default='BTech ECE\nMTech CSE\nB.Ed', max_length=50),
        ),
    ]
