# Generated by Django 5.0.4 on 2024-07-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_faculty_f_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_qualifications',
            field=models.CharField(default='BTech ECE,\nMTech CSE,\nB.Ed', max_length=50),
        ),
    ]
