# Generated by Django 5.0.4 on 2024-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_timetable_alter_syllabus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.CharField(choices=[('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM'), ('18:00:00', '06:00 PM')], max_length=8),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.CharField(choices=[('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM'), ('18:00:00', '06:00 PM')], max_length=8),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.CharField(choices=[('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM'), ('18:00:00', '06:00 PM')], max_length=8),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.CharField(choices=[('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM'), ('18:00:00', '06:00 PM')], max_length=8),
        ),
    ]
