# Generated by Django 5.0.4 on 2024-07-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_bus_arrival_time_alter_bus_departure_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='updated_at',
        ),
    ]
