# Generated by Django 5.0.4 on 2024-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_timetable_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_image',
            field=models.ImageField(blank=True, default='home/f_img/default.jpg', upload_to='home/f_img'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_image',
            field=models.ImageField(blank=True, default='home/s_img/default.jpg', upload_to='home/s_img'),
        ),
    ]
