# Generated by Django 5.0.4 on 2024-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_faculty_f_image_alter_student_s_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_imagename',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='s_imagename',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
